name: 刷步数

on:
  schedule:
    - cron: '19 9 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3  # 确认是否已经有更新的版本可用

      - name: 初始化Python
        uses: actions/setup-python@v3  # 确认是否已经有更新的版本可用
        with:
          python-version: 3.8

      - name: 安装依赖
        run: |
          pip3 install --upgrade pip
          pip3 install requests pytz

      - name: 开始
        env:
          CONFIG: ${{ secrets.CONFIG }}
        run: |
          python3 main.py
